### ISSUE TITLE
Cron management

### ISSUE THREAD

**Issue by Simon-Nuage** [nuage-studio/logik-frontend-template#123]
The purpose is to allow integrators to create tasks using the frontend.
To complete this issue, you will need : 

- To create an endpoint /api/tasks/hello-world
- To give a secret key to this endpoint (https://djecrety.ir/)
- Put this secret in the .env as a environment variable
- Put this secret key in the header in the github action

Ex : 

```
name: Hourly cron job
on:
  schedule:
    - cron: '*/60 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Hourly cron job
        run: |
          curl --request POST \
          --url 'https://example.com/api/task' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
```

Take a look here : https://github.com/paulphys/nextjs-cron
